name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install UV
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        uv sync --dev
    
    - name: Format check
      run: |
        uv run black --check . || true
      continue-on-error: true
    
    - name: Lint
      run: |
        uv run ruff check . || true
      continue-on-error: true
    
    - name: Type check
      run: |
        uv run mypy . --ignore-missing-imports || true
      continue-on-error: true
    
    - name: Test
      run: |
        uv run pytest -v --tb=short
    
    - name: Test with coverage (Python 3.11 only)
      if: matrix.python-version == '3.11'
      run: |
        uv run pytest --cov=. --cov-report=xml --cov-report=term-missing
    
    - name: Validate test cases
      run: |
        if [ -f "Makefile" ] && grep -q "validate:" Makefile; then
          make validate || echo "Validation step failed or not available"
        else
          echo "Makefile or validate target not found, skipping validation"
        fi
      continue-on-error: true
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: matrix.python-version == '3.11'
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
      continue-on-error: true

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install UV
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.11
    
    - name: Install dependencies
      run: uv sync --dev
    
    - name: Build package
      run: uv build
    
    - name: Store build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
